### ISSUE TITLE
Broken link for [MathBool Statements]

### ISSUE THREAD

**Issue by henrymly** [learn-co-curriculum/swift-mathBoolOp-lab#2]
# Switch Statements

 ### Readings associated with this lab
- [MathBool Statements](https://github.com/learn-co-curriculum/swift-MathBool-readme)
  
  */

Link is broken!

**Comment by AnnJohn** [comment]
hi @henrymly not sure what the issue here is or where it is in the lesson. could you please be a bit more specific?

**Comment by henrymly** [comment]
The link to the reading associated with this lab MathBool Statements is broken.

https://github.com/learn-co-curriculum/swift-MathBool-readme

leads to a github 404 page.

**Comment by AnnJohn** [comment]
i don't see this text in the lesson. if possible, could you provide a screenshot of what you see? thanks

**Comment by henrymly** [comment]
![screen shot 2016-09-06 at 9 26 06 am](https://cloud.githubusercontent.com/assets/2497911/18282071/4ba4fff4-7414-11e6-97be-254064840e84.png)
