### ISSUE TITLE
Playground file main is under comment

### ISSUE THREAD

**Issue by jaugeni** [learn-co-curriculum/swift-mathBoolOp-lab#3]
code is note running because the entire page under comment on main file 
![screen shot 2016-09-18 at 4 32 17 pm](https://cloud.githubusercontent.com/assets/17507128/18618872/97ddd186-7dbd-11e6-867a-6efdc7a56d57.png)

**Comment by AnnJohn** [comment]
@jaugeni you just need to remove the line with comments and then your code will run. thanks!
