### ISSUE TITLE
Playground formatting creates comments in documentation

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/swift-mathBoolOp-lab#4]
Something about the formatting of this playground makes it so when you write code it's commented.

![image](https://cloud.githubusercontent.com/assets/4515/20109953/52fe63f8-a5b0-11e6-935e-1b39c3af3007.png)

Also it seems that this is about Switch statements?

![image](https://cloud.githubusercontent.com/assets/4515/20109965/63866ad6-a5b0-11e6-8cdf-6bd12ceddfb4.png)

**Comment by jazzrubin** [comment]
This lab is not working, is there another link?

**Comment by JimCampagno** [comment]
Sorry for the late response. It's no longer a playground file, it's an Xcode lab which includes tests.

What I did to fix the lab:

![](https://media.giphy.com/media/gMe20azbhBiyQ/giphy.gif)

**Comment by jazzrubin** [comment]
Thanks so much

**Comment by jazzrubin** [comment]
Hey, it still not working

**Comment by JimCampagno** [comment]
Hey @jazzrubin , this lab has changed significantly. It no longer has you working in a Playground file, it now has you working in an Xcode project.

The problem (in your case) is that you've already forked the lab in its old state (which included the Playground file) and this doesn't reflect the fact that changes were made. There are a few ways to solve this problem to get your forked version of this lab to match the version of this lab that includes my changes.

Considering how much this lab has changed, I would recommend you follow the instructions in this video I made:

[![](http://img.youtube.com/vi/CsMDUFyyiNI/0.jpg)](https://www.youtube.com/watch?v=CsMDUFyyiNI "Re-fork")

After going through those instructions, you should be all good. If not, let me know of the specific issue you're having and what "isn't working".

Thanks.

**Comment by jazzrubin** [comment]
Thank you
