### ISSUE TITLE
Can't edit this lab

### ISSUE THREAD

**Issue by jazzrubin** [learn-co-curriculum/swift-mathBoolOp-lab#7]
<img width="1440" alt="screen shot 2016-12-21 at 5 13 42 pm" src="https://cloud.githubusercontent.com/assets/23643405/21408589/d2fec0b0-c7a3-11e6-8898-37dbbcd552ac.png">

**Comment by JimCampagno** [comment]
Thanks @jazzrubin 

I have just updated this lab, it's no longer a playground file. It's now an Xcode project which includes tests.
