### ISSUE TITLE
The title on the first line of the playground file is wrong

### ISSUE THREAD

**Issue by JJJV** [learn-co-curriculum/swift-mathBoolOp-lab#8]
The tittle of the lab is "Switch Statements"  but the lab is for booleans operators, the questions are correct and consistent with the materials on the previous lesson but the tittle is misleading some people.

**Comment by JJJV** [comment]
Also, currently it sits before the chapter on conditionals, but requires knowledge of conditionals.  It should be moved after the conditionals chapter.

**Comment by JimCampagno** [comment]
@JJJV Thanks!

I just updated this lab where it is no longer a playground file. It's now an Xcode project which includes tests. I also moved it after the conditional lab, thanks for the feedback.
