### ISSUE TITLE
Close comment formatting in Outline

### ISSUE THREAD

**Issue by ryans-git** [learn-co-curriculum/swift-mathBoolOp-lab#9]
needs a "*/" on line 11 to close the comment or the rest of the playground code is commented out

edit: and then remove the "*/" closure at the end on line 97. fixed the issues for me

**Comment by JimCampagno** [comment]
Thanks! I actually just changed up this lab where it is no longer a Playground file. Instead, it's an Xcode project that includes tests.

@ryan1twice
